version: '3'

services:
  gears-api-service:
    image: adxl/bng-api-gears:latest
    environment:
      STAGE: production
      DATABASE_URL: '@DATABASE_URL@'
      SENTRY_DSN: '@SENTRY_DSN@'
      BUCKET_URL: '@BUCKET_URL@'
      BUCKET_NAME: '@BUCKET_NAME@'
      AWS_S3_ACCESS_KEY: '@AWS_S3_ACCESS_KEY@'
      AWS_S3_SECRET_KEY: '@AWS_S3_SECRET_KEY@'
      AWS_S3_REGION: '@AWS_S3_REGION@'
      INTERNAL_BASIC: '@INTERNAL_BASIC@'
    networks:
      - bng
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s


networks:
  bng:
    external: true
