version: '3'

services:
  gears-api-service:
    build:
      context: .
      target: development
    env_file: .env
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"
    networks:
      - default
      - bng

  gears-db-service:
    image: postgres:13-alpine
    ports:
      - 54324:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - bng-gears-db-data:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
  bng-gears-db-data: {}

networks:
  default:
    driver: bridge
  bng:
    external: true
