version: '3'

services:
  gears-api-service:
    image: adxl/bng-api-gears:latest
    environment:
      STAGE: production
      DATABASE_URL: '@DATABASE_URL@'
      SENTRY_DSN: '@SENTRY_DSN@'
    networks:
      - bng
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s


networks:
  bng:
    external: true
